[project]
name = "diffusion-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.0.0",
    "diffusers>=0.35.0",
    "matplotlib>=3.8.0",
    "pillow>=10.0.0",
    "safetensors>=0.5.0",
    "torch>=2.1.0",
    "transformers>=4.50.0",
]
